### PR TITLE
Switched to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
Will reduce memory allocations.

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@n4gava ?

**Comment by n4gava** [comment]
I havent test it yet

**Comment by MarkCiliaVincenti** [comment]
> I havent test it yet

Gentle reminder :)

**Comment by MarkCiliaVincenti** [comment]
@n4gava

**Comment by MarkCiliaVincenti** [comment]
Why was this closed please? The existing code does not seem to clear semaphores from the dictionary and will persist in memory.

**Pull request closed without merging**
